### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement git

### ISSUE THREAD

**Issue by Pikamander2** [lobe/lobe-python#17]
When I try to run the Linux commands listed in the README.md, I get these errors:

```
pip3 install setuptools git
ERROR: Could not find a version that satisfies the requirement git (from versions: none)
ERROR: No matching distribution found for git
```

```
pip3 install git+https://github.com/lobe/lobe-python
ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git clone -q https://github.com/lobe/lobe-python /tmp/pip-req-build-1qql06x2
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
```

I'm using Ubuntu 20.04.1 LTS, Python 3.8.5, and pip 20.0.2.

**Comment by Pikamander2** [comment]
Based on some Stack Overflow answers, I ran this command instead:

```
pip3 install setuptools gitpython
```

However, that was causing the follow commands to say "Invalid requirement" and "It looks like a path. Does it exist?"

So instead, I went to [this page](https://git-scm.com/download/linux) and ran the commands it listed for Debian/Ubuntu:
```
sudo add-apt-repository ppa:git-core/ppa
sudo apt update
sudo apt install git
```

Afterwards, I also had to add `--no-cache-dir` to the end of the lobe installation command to avoid running out of memory, which is [a common problem](https://stackoverflow.com/a/54329850/1741346) when installing Tensorflow.

**Comment by mbeissinger** [comment]
Fixed with #18

**Comment by Pikamander2** [comment]
@mbeissinger - Whoops, I just realized that I left the "pip3 install git" part in, which means that it'll still throw an error. I'll make another pull request for that.
